In [6]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [7]:
df = pd.read_csv("movies_metadata.csv")

In [8]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [9]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [11]:
df.shape

(45466, 24)

In [12]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [13]:
df = df.drop_duplicates().reset_index(drop = True)

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df = df[['title', 'overview', 'genres','tagline','vote_average','popularity']]

In [16]:
df

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",NaN,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]",Just When His World Is Back To Normal... He's ...,5.7,8.387519
...,...,...,...,...,...,...
45448,Subdue,Rising and falling between a man and woman.,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",Rising and falling between a man and woman,4.0,0.072051
45449,Century of Birthing,An artist struggles to finish his work while a...,"[{'id': 18, 'name': 'Drama'}]",NaN,9.0,0.178241
45450,Betrayal,"When one of her hits goes wrong, a professiona...","[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",A deadly game of wits.,3.8,0.903007
45451,Satan Triumphant,"In a small town live two brothers, one a minis...",[],NaN,0.0,0.003503
45452,Queerama,50 years after decriminalisation of homosexual...,[],NaN,0.0,0.163015

In [17]:
df.isnull().sum()

title               6
overview          954
genres              0
tagline         25045
vote_average        6
popularity          5
dtype: int64

In [18]:
df = df.dropna(subset=['title'])

In [19]:
df['overview'] = df['overview'].fillna('')

In [20]:
df.iloc[0]['genres']

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [21]:
import ast

def get_genres(x):
    genres = ast.literal_eval(x)
    genre_names = []

    for genre in genres:
        genre_names.append(genre['name'])

    return " ".join(genre_names)

df['genres'] = df['genres'].apply(get_genres)

In [22]:
df.head()

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,NaN,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519

In [23]:
df['tagline'] = df['tagline'].fillna('')

In [24]:
df.isnull().sum()

title           0
overview        0
genres          0
tagline         0
vote_average    0
popularity      0
dtype: int64

In [25]:
df['tags'] = df['overview']+ " " + df['genres'] +" "+ df['tagline']

In [26]:
df.head()

,title,overview,genres,tagline,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519,Just when George Banks has recovered from his ...

In [27]:
df['tags'][1]

"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures. Adventure Fantasy Family Roll the dice and unleash the excitement!"

In [28]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [29]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [30]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [31]:
def preprocess_text(text):

    text = str(text)
    text = text.lower()

    text = re.sub(r'[^a-zA-Z\s]', '', text)

    words = text.split()

    clean_words = []

    for word in words:
        if word not in stop_words:
            word = lemmatizer.lemmatize(word)
            clean_words.append(word)

    return " ".join(clean_words)

In [32]:
df['tags'] = df['tags'].apply(preprocess_text)

In [33]:
df.head()

,title,overview,genres,tagline,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943,led woody andys toy live happily room andys bi...
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539,sibling judy peter discover enchanted board ga...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129,family wedding reignites ancient feud nextdoor...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495,cheated mistreated stepped woman holding breat...
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519,george bank recovered daughter wedding receive...

In [34]:
df = df.reset_index(drop = True)

In [35]:
indices = pd.Series(df.index,index = df['title']).drop_duplicates()
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45442
Century of Birthing            45443
Betrayal                       45444
Satan Triumphant               45445
Queerama                       45446
Length: 45447, dtype: int64

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=50000,
    ngram_range=(1, 2)
)

tfidf_matrix = tfidf.fit_transform(df['tags'])

tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1715627 stored elements and shape (45447, 50000)>

In [37]:
from sklearn.metrics.pairwise import cosine_similarity

def recommend(title, n=10):
    if title not in indices:
        return ['Movie not found']

    idx = indices[title]

    sim_score = cosine_similarity(
        tfidf_matrix[idx],
        tfidf_matrix
    ).flatten()

    similar_idx = sim_score.argsort()[::-1][1:n+1]

    return df['title'].iloc[similar_idx]

In [38]:
recommend('Avatar', 5)

26547                                      Avatar 2
13883                          The Inhabited Island
26553                                Thor: Ragnarok
43431                        Moontrap: Target Earth
6414     Lara Croft Tomb Raider: The Cradle of Life
Name: title, dtype: object

In [39]:
def precision_at_5(movie, relevant_movies):
    recommendations = recommend(movie, 5)

    relevant_count = 0

    for recommendation in recommendations:
        if recommendation in relevant_movies:
            relevant_count += 1

    precision = relevant_count / 5

    return precision

In [40]:
test_movies = {
    'Avatar': [
        'Avatar 2'
    ],

    'Inception': [
        # add relevant movies here
    ]
}

In [41]:
for movie, relevant_movies in test_movies.items():
    score = precision_at_5(movie, relevant_movies)
    print(movie, "Precision@5:", score)

Avatar Precision@5: 0.2
Inception Precision@5: 0.0

In [42]:
recommend('Avatar', 5)

26547                                      Avatar 2
13883                          The Inhabited Island
26553                                Thor: Ragnarok
43431                        Moontrap: Target Earth
6414     Lara Croft Tomb Raider: The Cradle of Life
Name: title, dtype: object

In [43]:
recommend('Inception', 5)

7459                           Cypher
5310                  Minority Report
44425                           Gamer
39953    UFO - Distruggete base Luna!
44084                     Mechenosets
Name: title, dtype: object

In [44]:
test_movies = {
    'Avatar': [
        'Avatar 2',
        'The Inhabited Island',
        'Moontrap: Target Earth'
    ],

    'Inception': [
        'Cypher',
        'Minority Report'
    ]
}

In [45]:
for movie, relevant_movies in test_movies.items():
    score = precision_at_5(movie, relevant_movies)
    print(movie, "Precision@5:", score)

Avatar Precision@5: 0.6
Inception Precision@5: 0.4

In [46]:
results = []

for movie, relevant_movies in test_movies.items():

    score = precision_at_5(movie, relevant_movies)

    results.append({
        'Movie': movie,
        'Precision@5': score
    })

results_df = pd.DataFrame(results)

print(results_df)
print("\nAverage Precision@5:", results_df['Precision@5'].mean())

       Movie  Precision@5
0     Avatar          0.6
1  Inception          0.4

Average Precision@5: 0.5

In [47]:
import pickle

pickle.dump(tfidf_matrix, open('tfidf_matrix.pkl', 'wb'))
pickle.dump(indices, open('indices.pkl', 'wb'))
df.to_pickle('df.pkl')
pickle.dump(tfidf, open('tfidf.pkl', 'wb'))

In [48]:
import numpy as np
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import ndcg_score

In [49]:
import numpy as np
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import ndcg_score

In [50]:
df = df.reset_index(drop=True)

indices = pd.Series(
    df.index,
    index=df['title']
).drop_duplicates()

print("Number of movies:", len(df))
print("Number of unique titles:", df['title'].nunique())

Number of movies: 45447
Number of unique titles: 42277

In [51]:
tfidf_uni = TfidfVectorizer(
    max_features=50000,
    ngram_range=(1, 1)
)

tfidf_uni_matrix = tfidf_uni.fit_transform(df['tags'])

print("Unigram TF-IDF shape:", tfidf_uni_matrix.shape)

Unigram TF-IDF shape: (45447, 50000)

In [65]:
def recommend_unigram(title, n=10):

    if title not in indices:
        return []

    # Get the first index in case there are duplicate titles
    idx = indices[title]
    if isinstance(idx, pd.Series):
        idx = idx.iloc[0]

    similarity_scores = cosine_similarity(
        tfidf_uni_matrix[idx],
        tfidf_uni_matrix
    ).flatten()

    similar_indices = similarity_scores.argsort()[::-1][1:n+1]

    return df['title'].iloc[similar_indices].tolist()

In [53]:
tfidf_bi = TfidfVectorizer(
    max_features=50000,
    ngram_range=(1, 2)
)

tfidf_bi_matrix = tfidf_bi.fit_transform(df['tags'])

print("Unigram + Bigram TF-IDF shape:", tfidf_bi_matrix.shape)

Unigram + Bigram TF-IDF shape: (45447, 50000)

In [66]:
def recommend_bigram(title, n=10):

    if title not in indices:
        return []

    # Get the first index in case there are duplicate titles
    idx = indices[title]
    if isinstance(idx, pd.Series):
        idx = idx.iloc[0]

    similarity_scores = cosine_similarity(
        tfidf_bi_matrix[idx],
        tfidf_bi_matrix
    ).flatten()

    similar_indices = similarity_scores.argsort()[::-1][1:n+1]

    return df['title'].iloc[similar_indices].tolist()

In [55]:
recommend_bigram("Avatar", 5)

['Avatar 2',
 'The Inhabited Island',
 'Thor: Ragnarok',
 'Moontrap: Target Earth',
 'Lara Croft Tomb Raider: The Cradle of Life']

In [56]:
test_movies = {
    "Avatar": [
        "Avatar 2",
        "The Inhabited Island",
        "Moontrap: Target Earth"
    ],

    "Inception": [
        "Cypher",
        "Minority Report"
    ],

    "The Dark Knight": [
        "Batman Begins",
        "The Dark Knight Rises"
    ],

    "Titanic": [
        "The Notebook",
        "A Walk in the Clouds"
    ],

    "Toy Story": [
        "Toy Story 2",
        "Toy Story 3"
    ]
}

In [57]:
for movie, relevant in test_movies.items():

    print("\n", movie)

    for r in relevant:
        print(r, "->", r in indices)

 Avatar
Avatar 2 -> True
The Inhabited Island -> True
Moontrap: Target Earth -> True

 Inception
Cypher -> True
Minority Report -> True

 The Dark Knight
Batman Begins -> True
The Dark Knight Rises -> True

 Titanic
The Notebook -> True
A Walk in the Clouds -> True

 Toy Story
Toy Story 2 -> True
Toy Story 3 -> True

In [58]:
def precision_at_k(recommendations, relevant_movies, k):

    recommendations = recommendations[:k]

    relevant_count = 0

    for movie in recommendations:
        if movie in relevant_movies:
            relevant_count += 1

    return relevant_count / k

In [59]:
recommendations = [
    "Avatar 2",
    "The Inhabited Island",
    "Random Movie",
    "Moontrap: Target Earth",
    "Another Movie"
]

relevant = [
    "Avatar 2",
    "The Inhabited Island",
    "Moontrap: Target Earth"
]

print(precision_at_k(recommendations, relevant, 5))

0.6

In [60]:
def recall_at_k(recommendations, relevant_movies, k):

    recommendations = recommendations[:k]

    relevant_count = 0

    for movie in recommendations:
        if movie in relevant_movies:
            relevant_count += 1

    if len(relevant_movies) == 0:
        return 0

    return relevant_count / len(relevant_movies)

In [61]:
def ndcg_at_k(recommendations, relevant_movies, k):

    recommendations = recommendations[:k]

    relevance = []

    for movie in recommendations:
        if movie in relevant_movies:
            relevance.append(1)
        else:
            relevance.append(0)

    if len(relevance) == 0:
        return 0

    ideal_relevance = sorted(relevance, reverse=True)

    return ndcg_score(
        [ideal_relevance],
        [relevance]
    )

In [62]:
recommendations = [
    "Avatar 2",
    "Random Movie",
    "The Inhabited Island",
    "Another Movie",
    "Moontrap: Target Earth"
]

relevant = [
    "Avatar 2",
    "The Inhabited Island",
    "Moontrap: Target Earth"
]

print(ndcg_at_k(recommendations, relevant, 5))

0.8584912361856167

In [63]:
def evaluate_model(recommend_function, test_movies):

    results = []

    for movie, relevant_movies in test_movies.items():

        recommendations = recommend_function(movie, 10)

        p5 = precision_at_k(
            recommendations,
            relevant_movies,
            5
        )

        p10 = precision_at_k(
            recommendations,
            relevant_movies,
            10
        )

        r5 = recall_at_k(
            recommendations,
            relevant_movies,
            5
        )

        r10 = recall_at_k(
            recommendations,
            relevant_movies,
            10
        )

        n5 = ndcg_at_k(
            recommendations,
            relevant_movies,
            5
        )

        n10 = ndcg_at_k(
            recommendations,
            relevant_movies,
            10
        )

        results.append({
            "Movie": movie,
            "Precision@5": p5,
            "Precision@10": p10,
            "Recall@5": r5,
            "Recall@10": r10,
            "NDCG@5": n5,
            "NDCG@10": n10
        })

    return pd.DataFrame(results)

In [67]:
unigram_results = evaluate_model(
    recommend_unigram,
    test_movies
)

unigram_results

,Movie,Precision@5,Precision@10,Recall@5,Recall@10,NDCG@5,NDCG@10
0,Avatar,0.0,0.0,0.0,0.0,0.0,0.000000
1,Inception,0.0,0.0,0.0,0.0,0.0,0.000000
2,The Dark Knight,0.2,0.2,0.5,1.0,1.0,0.723234
3,Titanic,0.0,0.0,0.0,0.0,0.0,0.000000
4,Toy Story,0.4,0.2,1.0,1.0,1.0,1.000000

In [68]:
unigram_results = evaluate_model(recommend_unigram, test_movies)
bigram_results = evaluate_model(recommend_bigram, test_movies)

print("--- Unigram Results ---")
print(unigram_results)
print("\n--- Bigram Results ---")
print(bigram_results)

--- Unigram Results ---
             Movie  Precision@5  Precision@10  Recall@5  Recall@10  NDCG@5  \
0           Avatar          0.0           0.0       0.0        0.0     0.0
1        Inception          0.0           0.0       0.0        0.0     0.0
2  The Dark Knight          0.2           0.2       0.5        1.0     1.0
3          Titanic          0.0           0.0       0.0        0.0     0.0
4        Toy Story          0.4           0.2       1.0        1.0     1.0

    NDCG@10
0  0.000000
1  0.000000
2  0.723234
3  0.000000
4  1.000000

--- Bigram Results ---
             Movie  Precision@5  Precision@10  Recall@5  Recall@10    NDCG@5  \
0           Avatar          0.6           0.3       1.0        1.0  0.858491
1        Inception          0.4           0.2       1.0        1.0  1.000000
2  The Dark Knight          0.2           0.1       0.5        0.5  1.000000
3          Titanic          0.0           0.0       0.0        0.0  0.000000
4        Toy Story          0.4           0.2       1.0        1.0  1.000000

    NDCG@10
0  0.828409
1  1.000000
2  1.000000
3  0.000000
4  1.000000

In [69]:
test_movies = {
    "Avatar": [
        "Avatar 2",
        "The Inhabited Island",
        "Moontrap: Target Earth",
        "Lara Croft Tomb Raider: The Cradle of Life"
    ],

    "Inception": [
        "Cypher",
        "Minority Report",
        "Gamer",
        "The Matrix"
    ],

    "The Dark Knight": [
        "Batman Begins",
        "The Dark Knight Rises",
        "Batman",
        "Batman Returns"
    ],

    "Titanic": [
        "The Notebook",
        "A Walk in the Clouds",
        "Romeo + Juliet",
        "Pearl Harbor"
    ],

    "Toy Story": [
        "Toy Story 2",
        "Toy Story 3",
        "A Bug's Life",
        "Monsters, Inc."
    ],

    "The Matrix": [
        "The Matrix Reloaded",
        "The Matrix Revolutions",
        "Terminator 2: Judgment Day",
        "Minority Report"
    ],

    "Jurassic Park": [
        "The Lost World: Jurassic Park",
        "Jurassic Park III",
        "Jurassic World",
        "The Lost World"
    ],

    "Gladiator": [
        "Troy",
        "Kingdom of Heaven",
        "Spartacus",
        "300"
    ],

    "The Lord of the Rings: The Fellowship of the Ring": [
        "The Lord of the Rings: The Two Towers",
        "The Lord of the Rings: The Return of the King",
        "The Hobbit: An Unexpected Journey",
        "The Hobbit: The Desolation of Smaug"
    ],

    "Harry Potter and the Philosopher's Stone": [
        "Harry Potter and the Chamber of Secrets",
        "Harry Potter and the Prisoner of Azkaban",
        "Harry Potter and the Goblet of Fire",
        "Harry Potter and the Order of the Phoenix"
    ]
}

In [70]:
valid_test_movies = {}

for movie, relevant_movies in test_movies.items():

    if movie not in indices:
        print("Skipping missing test movie:", movie)
        continue

    valid_relevant = []

    for relevant in relevant_movies:
        if relevant in indices:
            valid_relevant.append(relevant)
        else:
            print("Missing relevant movie:", relevant)

    if len(valid_relevant) > 0:
        valid_test_movies[movie] = valid_relevant

print("\nValid test movies:", len(valid_test_movies))

Valid test movies: 10

In [71]:
for movie, relevant_movies in valid_test_movies.items():

    print("\n" + movie)
    print("Relevant movies:", relevant_movies)

Avatar
Relevant movies: ['Avatar 2', 'The Inhabited Island', 'Moontrap: Target Earth', 'Lara Croft Tomb Raider: The Cradle of Life']

Inception
Relevant movies: ['Cypher', 'Minority Report', 'Gamer', 'The Matrix']

The Dark Knight
Relevant movies: ['Batman Begins', 'The Dark Knight Rises', 'Batman', 'Batman Returns']

Titanic
Relevant movies: ['The Notebook', 'A Walk in the Clouds', 'Romeo + Juliet', 'Pearl Harbor']

Toy Story
Relevant movies: ['Toy Story 2', 'Toy Story 3', "A Bug's Life", 'Monsters, Inc.']

The Matrix
Relevant movies: ['The Matrix Reloaded', 'The Matrix Revolutions', 'Terminator 2: Judgment Day', 'Minority Report']

Jurassic Park
Relevant movies: ['The Lost World: Jurassic Park', 'Jurassic Park III', 'Jurassic World', 'The Lost World']

Gladiator
Relevant movies: ['Troy', 'Kingdom of Heaven', 'Spartacus', '300']

The Lord of the Rings: The Fellowship of the Ring
Relevant movies: ['The Lord of the Rings: The Two Towers', 'The Lord of the Rings: The Return of the King', 'The Hobbit: An Unexpected Journey', 'The Hobbit: The Desolation of Smaug']

Harry Potter and the Philosopher's Stone
Relevant movies: ['Harry Potter and the Chamber of Secrets', 'Harry Potter and the Prisoner of Azkaban', 'Harry Potter and the Goblet of Fire', 'Harry Potter and the Order of the Phoenix']

In [72]:
total_relevant_movies = sum(
    len(relevant_movies)
    for relevant_movies in valid_test_movies.values()
)

print("Test queries:", len(valid_test_movies))
print("Total relevant movie labels:", total_relevant_movies)

Test queries: 10
Total relevant movie labels: 40

In [73]:
unigram_results = evaluate_model(
    recommend_unigram,
    valid_test_movies
)

bigram_results = evaluate_model(
    recommend_bigram,
    valid_test_movies
)

In [74]:
display(
    unigram_results.round(4)
)

,Movie,Precision@5,Precision@10,Recall@5,Recall@10,NDCG@5,NDCG@10
0,Avatar,0.2,0.1,0.25,0.25,0.4871,0.3937
1,Inception,0.0,0.0,0.00,0.00,0.0000,0.0000
2,The Dark Knight,0.4,0.3,0.50,0.75,1.0000,0.8284
3,Titanic,0.0,0.0,0.00,0.00,0.0000,0.0000
4,Toy Story,0.4,0.2,0.50,0.50,1.0000,1.0000
5,The Matrix,0.0,0.0,0.00,0.00,0.0000,0.0000
6,Jurassic Park,0.2,0.1,0.25,0.25,1.0000,1.0000
7,Gladiator,0.0,0.0,0.00,0.00,0.0000,0.0000
8,The Lord of the Rings: The Fellowship of the Ring,0.0,0.3,0.00,0.75,0.0000,0.4852
9,Harry Potter and the Philosopher's Stone,0.6,0.4,0.75,1.00,1.0000,0.8790

In [75]:
display(
    bigram_results.round(4)
)

,Movie,Precision@5,Precision@10,Recall@5,Recall@10,NDCG@5,NDCG@10
0,Avatar,0.8,0.4,1.00,1.00,0.9010,0.8790
1,Inception,0.6,0.3,0.75,0.75,1.0000,1.0000
2,The Dark Knight,0.4,0.2,0.50,0.50,0.7693,0.7232
3,Titanic,0.0,0.0,0.00,0.00,0.0000,0.0000
4,Toy Story,0.4,0.2,0.50,0.50,1.0000,1.0000
5,The Matrix,0.0,0.0,0.00,0.00,0.0000,0.0000
6,Jurassic Park,0.2,0.1,0.25,0.25,1.0000,1.0000
7,Gladiator,0.0,0.0,0.00,0.00,0.0000,0.0000
8,The Lord of the Rings: The Fellowship of the Ring,0.4,0.4,0.50,1.00,0.5386,0.6369
9,Harry Potter and the Philosopher's Stone,0.8,0.4,1.00,1.00,0.9010,0.8790

In [79]:
import pickle

pickle.dump(tfidf_bi, open("tfidf_bi.pkl", "wb"))
pickle.dump(tfidf_bi_matrix, open("tfidf_bi_matrix.pkl", "wb"))